---
- name: Manage LVM volume group
  lvg:
    vg: "{{ vgname }}"
    pvs: "/dev/{{ disk }}"
    state: present

- name: Manage LVM logical volume
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname }}"
    size: "{{ lvsize }}"
    resizefs: yes
    state: present

- name: Creating new filesystem on new LVM logical volume
  filesystem:
    fstype: "{{ filesystem | default('xfs') }}"
    dev: "/dev/{{ vgname }}/{{ lvname }}"

- name:  Mounting new filesystem
  mount:
    path: "/{{ mount_point }}"
    src: "/dev/mapper/{{ vgname }}-{{ lvname }}"
    fstype: "{{ filesystem }}"
    state: mounted
    opts: rw,defaults

