---
- name: Create a directory if it does not exist
  file:
    path: /home/openshift-volumes
    state: directory
    mode: '0755'

- name: customize Templates
  template:
    src: "templates/{{ item.src }}"
    dest: "/home/openshift-volumes/{{ item.dest }}"
    mode: '0755'
  loop:
    - { src: 'rwo-pv-gluster.j2', dest: 'rwo-pv-gluster.sh' }
    - { src: 'rwx-pv-pvc-gluster.j2', dest: 'rwx-pv-pvc-gluster.sh' }
      
    
